name: Build
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Check Code Style
              run: cargo fmt --check
            - name: Run Unit Tests
              run: cargo test
            - name: Build Image
              uses: docker/build-push-action@v5
              with:
                  file: ./Dockerfile
                  push: false
                  tags: abacus-pns:latest