name: Build
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Check code style
              run: cargo fmt --check
            - name: Build
              uses: docker/build-push-action@v5
              with:
                  file: ./Dockerfile
                  push: false
                  tags: abacus-pns:latest